version: '3.8'
services:
  db:
    network_mode: host
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=team
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - spring-cloud-network
volumes:
  db:
    driver: local
networks:
  spring-cloud-network:
    driver: bridge