version: '3'
services:
  app-server:
    container_name: team-mgmnt
    build:
      dockerfile: Dockerfile
    image: sample/team-mgmnt-docker:latest
    ports:
      - "8090:8080"
      - "5005:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - spring-cloud-network
    depends_on:
      - db
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=team
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - spring-cloud-network
volumes:
  db:
    driver: local
networks:
  spring-cloud-network:
    driver: bridge