version: '3'
services:
  app-server:
    container_name: team-mgmnt
    build:
      dockerfile: Dockerfile
    image: sample/team-mgmnt-docker:latest
    ports:
      - "8090:8080"
      - "5005:5005"
    environment:
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge